# Generated by Django 4.2.1 on 2023-06-11 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={},
        ),
    ]
