# Generated by Django 4.2.1 on 2023-06-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultsettings',
            name='default_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
