# Generated by Django 4.2.1 on 2023-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_management_app', '0002_alter_studentresult_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresult',
            name='subject_assignment_marks',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject_exam_marks',
            field=models.FloatField(),
        ),
    ]
